#! /usr/bin/env python3
from pwd import *
import string
import math
import pandas

alphabet = string.ascii_lowercase+string.digits+'CTF{_}'

plain_flag = ''
known = []
r = remote("mercury.picoctf.net", 6276)
prompt = r.recvuntil("flag: ")
cipher_flag = r.recvline().strip().decode()
print("Flag is : " + cipher_flag)
r.recvline()
r.recvline()

while '}' not in plain_flag:
    for c in alphabet:
        playload = plain_flag+c
        r.sendafter("give me: ", playload+"\n")
        prompt = r.recvuntil("Here you go: ")
        cipher = r.recvline().strip().decode()
        for chunck in known:
            cipher = cipher.replace(chunck, '')
            if (cipher in cipher_flag):
                cipher_flag = cipher_flag.replace(cipher, '')
                known.append(cipher)
                plain_flag += c
                print(plain_flag)
                break