name: Display
on: [push]
jobs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            run:
                echo ${{Github.branch.base.ref}}
                du -skh --exclude=" .git"
